import type { Metadata } from "next";
import { Inter, Onest } from "next/font/google";
import "./globals.css";

// Onest font from Google Fonts
const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"], // Regular, Medium, SemiBold, Bold
});

// Inter font from Google Fonts
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${onest.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
